import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Header, Navbar } from "@/components";
import { Footer } from "@/components";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
          <Header />
          <Navbar 
            color="#5383E8"
            links={[
              { href: "/", label: "홈" },
              { href: "/stats", label: "통계" },
            ]}
          />

          <main className="flex flex-1 flex-col">{children}</main>

          <Footer />
        </body>
    </html>
  );
}
